### ISSUE TITLE
Issue with Tables

### ISSUE THREAD

**Issue by omar319** [Michael-Goldfarb/MLBGamePredictor#1]
Hello,

I ran everything according to your README but is there a way to create past tables? when running prediction1 it is looking for this :: `[SQL: SELECT * FROM PitchingStats2022]` I have tried running your past tables as well and get errors such as these ::

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./MLBGamePredictorUI/MLBGamePredictorBackEnd/Tables/PastTables/PreviousYearHittingStats2022.py", line 77, in <module>
    data = response.json()
  File "/usr/local/lib/python3.10/dist-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Michael-Goldfarb** [comment]
Hi Omar,

The issue is that I stored the database information locally on my computer,
preventing you from connecting to the database. I will work on a solution
to overcome this problem.

**Comment by Michael-Goldfarb** [comment]
Try again now, I have output instructions on how to create past tables

**Comment by Michael-Goldfarb** [comment]
Try again now, I have output instructions on how to create past tables
